/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.xprod.xproddesktop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author william NYACKA
 */
public class Fournisseur extends javax.swing.JFrame {

    /**
     * Creates new form Fournisseur
     */
    public Fournisseur() {
        initComponents();
        this.setTitle("XPROD Fournisseurs - Administrateur");
        tableUpdate(); //Mettre à jour la table des fournisseurs
    }

    //Connexion
    Connection con;
    PreparedStatement pst;

    //Mise à jour du tableau
    private void tableUpdate() {
        int cpt;// déclaration d'une variable que je nomme compteur

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");//Register de MySQL Driver
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xproddb", "root", "");
            String query = "SELECT * FROM fournisseur";
            pst = con.prepareStatement(query);

            ResultSet rs = pst.executeQuery(); //Je mets mes données dans un tableau de résultat

            ResultSetMetaData rsmd = rs.getMetaData();// Je récupère toute mes métadonnées du tableau de résultat
            cpt = rsmd.getColumnCount();// Je compte toute mes métadonnées

            DefaultTableModel dtm = (DefaultTableModel) tableFournisseur.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {//Tant que j'ai des données dans mon tableau de résultat
                Vector vect = new Vector();
                vect.add(rs.getString("idFournisseur"));
                vect.add(rs.getString("nomFournisseur"));
                vect.add(rs.getString("rsFournisseur"));
                vect.add(rs.getString("rueFournisseur"));
                vect.add(rs.getString("cpFournisseur"));
                vect.add(rs.getString("villeFournisseur"));
                vect.add(rs.getString("paysFournisseur"));
                vect.add(rs.getString("telFournisseur"));
                vect.add(rs.getString("faxFournisseur"));
                vect.add(rs.getString("emailFournisseur"));
                dtm.addRow(vect);
            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtRue = new javax.swing.JTextField();
        txtCodePostal = new javax.swing.JTextField();
        txtVille = new javax.swing.JTextField();
        txtPays = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtRS = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFournisseur = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemProduit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemFournisseur = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCommande = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemSeDeconnecter = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(237, 182, 54));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("Nom");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("Raison sociale");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("Rue");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("Code postal");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("Ville");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setText("Pays");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("Téléphone");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setText("Fax");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setText("Email");

        tableFournisseur.setBackground(new java.awt.Color(0, 0, 0));
        tableFournisseur.setForeground(new java.awt.Color(255, 255, 255));
        tableFournisseur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identifiant", "Nom", "Raison sociale", "Rue", "Code postal", "Ville", "Pays", "Téléphone", "Fax", "Email"
            }
        ));
        tableFournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFournisseurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFournisseur);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fournisseur");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        btnSupprimer.setText("Supprimer");
        btnSupprimer.setBorder(null);
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.setBorder(null);
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.setBorder(null);
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(txtRue))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtPays, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(txtFax, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtTel)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu4.setText("Produit");

        jMenuItemProduit.setText("Ajouter un produit");
        jMenuItemProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProduitActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemProduit);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Fournisseur");

        jMenuItemFournisseur.setText("Ajouter un fournisseur");
        jMenuItemFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFournisseurActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFournisseur);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Commande");

        jMenuItemCommande.setText("Ajouter une commande");
        jMenuItemCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCommandeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCommande);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Déconnexion");

        jMenuItemSeDeconnecter.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItemSeDeconnecter.setText("Se déconnecter");
        jMenuItemSeDeconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeDeconnecterActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemSeDeconnecter);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // Je récupère les informations entrées dans nos textes
        //String idProduit = txtID.getText(); AUTO INCREMENT
        String nomFournisseur = txtNom.getText();
        String rsFournisseur = txtRS.getText();
        String rueFournisseur = txtRue.getText();
        String cpFournisseur = txtCodePostal.getText();
        String villeFournisseur = txtVille.getText();
        String paysFournisseur = txtPays.getText();
        String telFournisseur = txtTel.getText();
        String faxFournisseur = txtFax.getText();
        String emailFournisseur = txtEmail.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");//Register de MySQL Driver

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xproddb", "root", "");

            pst = con.prepareStatement("insert into fournisseur (nomFournisseur, rsFournisseur, rueFournisseur, cpFournisseur, villeFournisseur, paysFournisseur, telFournisseur, faxFournisseur, emailFournisseur) values (?,?,?,?,?,?,?,?,?)");

            pst.setString(1, nomFournisseur);
            pst.setString(2, rsFournisseur);
            pst.setString(3, rueFournisseur);
            pst.setString(4, cpFournisseur);
            pst.setString(5, villeFournisseur);
            pst.setString(6, paysFournisseur);
            pst.setString(7, telFournisseur);
            pst.setString(8, faxFournisseur);
            pst.setString(9, emailFournisseur);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Données enregistrées");

            //Vider les champs après le message
            txtNom.setText("");
            txtRS.setText("");
            txtRue.setText("");
            txtCodePostal.setText("");
            txtVille.setText("");
            txtPays.setText("");
            txtTel.setText("");
            txtFax.setText("");
            txtEmail.setText("");

            tableUpdate();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // Modification
        DefaultTableModel dtm = (DefaultTableModel) tableFournisseur.getModel();

        int selectedIndex = tableFournisseur.getSelectedRow();

        try {
            int IDFournisseur = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());//ID de la table fournisseur

            String nomFournisseur = txtNom.getText();
            String rsFournisseur = txtRS.getText();
            String rueFournisseur = txtRue.getText();
            String cpFournisseur = txtCodePostal.getText();
            String villeFournisseur = txtVille.getText();
            String paysFournisseur = txtPays.getText();
            String telFournisseur = txtTel.getText();
            String faxFournisseur = txtFax.getText();
            String emailFournisseur = txtEmail.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");//Register de MySQL Driver

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xproddb", "root", "");

            pst = con.prepareStatement("update fournisseur set nomfournisseur=?, rsfournisseur=?, ruefournisseur=?, cpfournisseur=?, villefournisseur=?, paysfournisseur=?, telfournisseur=?, faxfournisseur=?, emailfournisseur=? where idfournisseur=?");

            pst.setString(1, nomFournisseur);
            pst.setString(2, rsFournisseur);
            pst.setString(3, rueFournisseur);
            pst.setString(4, cpFournisseur);
            pst.setString(5, villeFournisseur);
            pst.setString(6, paysFournisseur);
            pst.setString(7, telFournisseur);
            pst.setString(8, faxFournisseur);
            pst.setString(9, emailFournisseur);
            pst.setInt(10, IDFournisseur);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Données mise à jour");

            //Vider les champs après le message
            txtNom.setText("");
            txtRS.setText("");
            txtRue.setText("");
            txtCodePostal.setText("");
            txtVille.setText("");
            txtPays.setText("");
            txtTel.setText("");
            txtFax.setText("");
            txtEmail.setText("");

            tableUpdate();//Mettre à jour la table des produits

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        //Supprimer
        DefaultTableModel dtm = (DefaultTableModel) tableFournisseur.getModel();
        int selectedIndex = tableFournisseur.getSelectedRow();
        int IDFournisseur = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());  //Id de la table produit 

        int dialogResult = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette données ?", "ATTENTION!", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");   //Register de MySQL Diver
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xproddb", "root", "");
                pst = con.prepareStatement("delete from fournisseur where idFournisseur=?");
                pst.setInt(1, IDFournisseur);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Données supprimées !");

                //Je vide le contenu des champs remplis
                txtNom.setText("");
                txtRS.setText("");
                txtRue.setText("");
                txtCodePostal.setText("");
                txtVille.setText("");
                txtPays.setText("");
                txtTel.setText("");
                txtFax.setText("");
                txtEmail.setText("");

                tableUpdate(); //Mettre à jour la table des produits

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(XprodDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void tableFournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFournisseurMouseClicked
        // Pour séléctionner les informations d'un champ
        DefaultTableModel dtm = (DefaultTableModel) tableFournisseur.getModel();

        int selectedIndex = tableFournisseur.getSelectedRow();

        txtNom.setText(dtm.getValueAt(selectedIndex, 1).toString());
        txtRS.setText(dtm.getValueAt(selectedIndex, 2).toString());
        txtRue.setText(dtm.getValueAt(selectedIndex, 3).toString());
        txtCodePostal.setText(dtm.getValueAt(selectedIndex, 4).toString());
        txtVille.setText(dtm.getValueAt(selectedIndex, 5).toString());
        txtPays.setText(dtm.getValueAt(selectedIndex, 6).toString());
        txtTel.setText(dtm.getValueAt(selectedIndex, 7).toString());
        txtFax.setText(dtm.getValueAt(selectedIndex, 8).toString());
        txtEmail.setText(dtm.getValueAt(selectedIndex, 9).toString());
    }//GEN-LAST:event_tableFournisseurMouseClicked

    private void jMenuItemFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFournisseurActionPerformed
        Fournisseur AjoutFournisseur = new Fournisseur();
        AjoutFournisseur.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemFournisseurActionPerformed

    private void jMenuItemCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCommandeActionPerformed
        Commande AjoutCommande = new Commande();
        AjoutCommande.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCommandeActionPerformed

    private void jMenuItemSeDeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeDeconnecterActionPerformed
        Login connexion = new Login();
        connexion.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSeDeconnecterActionPerformed

    private void jMenuItemProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProduitActionPerformed
        XprodDesktop produit = new XprodDesktop();
        produit.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemProduitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fournisseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemCommande;
    private javax.swing.JMenuItem jMenuItemFournisseur;
    private javax.swing.JMenuItem jMenuItemProduit;
    private javax.swing.JMenuItem jMenuItemSeDeconnecter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFournisseur;
    private javax.swing.JTextField txtCodePostal;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPays;
    private javax.swing.JTextField txtRS;
    private javax.swing.JTextField txtRue;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
